---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Ubuntu)
    tags: always
    package:
      upgrade: dist
      update_cache: yes
    when: ansible_facts['distribution'] == "Ubuntu"

- hosts: workstations
  become: true
  tasks:

  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.16.5/terraform_1.16.5_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root


- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 package and php packages for Ubuntu
    tags: apache, apache2, ubuntu
    package:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_facts['distribution'] == "Ubuntu"

  - name: copy default html file for site
    tags: apache, apache2
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644


- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (Ubuntu)
    tags: mariadb, ubuntu
    package:
      name: mariadb-server
      state: latest
    when: ansible_facts['distribution'] == "Ubuntu"


- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: ubuntu, samba
    package:
      name: samba
      state: latest

